const actionTypes = {
  GET_HOME: 'GET_HOME',
  SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
  SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
  SET_CUR_ALBUM_ID: 'SET_CUR_ALBUM_ID',
  LOADING: 'LOADING',
  SET_RECENT: 'SET_RECENT',

  // // music
  PLAY: 'PLAY',
  // SET_ALBUM: 'SET_ALBUM',
  // PLAYLIST: 'PLAYLIST',
  // SEARCH: 'SEARCH',
  GET_ALL_SONG: 'GET_ALL_SONG',
  GET_SONG: 'GET_SONG',
  GET_TOP_TEN: 'GET_TOP_TEN',
  GET_TOP_NATION: 'GET_TOP_NATION',
  GET_GENRE_POP: 'GET_GENRE_POP',
  GET_GENRE_EDM: 'GET_GENRE_EDM',
}

export default actionTypes
